config/routes.rb
Rails.application.routes.draw do
  resources :routers
  # get '/routers/new',to: 'routers#new'
  # get '/routers/new', to: 'routers#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/router.rb
class Router < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/routers_controller.rb
class RoutersController < ApplicationController
  before_action :set_router, only: [:show, :edit, :update, :destroy]

  # GET /routers
  # GET /routers.json
  def index
    @routers = Router.all
  end

  # GET /routers/1
  # GET /routers/1.json
  def show
  end

  # GET /routers/new
  def new
    @router = Router.new
  end

  # GET /routers/1/edit
  def edit
  end

  # POST /routers
  # POST /routers.json
  def create
    @router = Router.new(router_params)

    respond_to do |format|
      if @router.save
        format.html { redirect_to @router, notice: 'Router was successfully created.' }
        format.json { render :show, status: :created, location: @router }
      else
        format.html { render :new }
        format.json { render json: @router.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routers/1
  # PATCH/PUT /routers/1.json
  def update
    respond_to do |format|
      if @router.update(router_params)
        format.html { redirect_to @router, notice: 'Router was successfully updated.' }
        format.json { render :show, status: :ok, location: @router }
      else
        format.html { render :edit }
        format.json { render json: @router.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routers/1
  # DELETE /routers/1.json
  def destroy
    @router.destroy
    respond_to do |format|
      format.html { redirect_to routers_url, notice: 'Router was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_router
      @router = Router.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def router_params
      params.require(:router).permit(:name, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/routers_helper.rb
module RoutersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GmapApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script src="//maps.google.com/maps/api/js?key=[your API key]"></script>  
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>  
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
    <script src='//underscorejs.org/underscore-min.js' type='text/javascript'></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/routers/_form.html.erb
<%= form_with(model: router, local: true) do |form| %>
  <% if router.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(router.errors.count, "error") %> prohibited this router from being saved:</h2>

      <ul>
      <% router.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/routers/edit.html.erb
<h1>Editing Router</h1>

<%= render 'form', router: @router %>

<%= link_to 'Show', @router %> |
<%= link_to 'Back', routers_path %>

app/views/routers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Routers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routers.each do |router| %>
      <tr>
        <td><%= router.name %></td>
        <td><%= router.latitude %></td>
        <td><%= router.longitude %></td>
        <td><%= link_to 'Show', router %></td>
        <td><%= link_to 'Edit', edit_router_path(router) %></td>
        <td><%= link_to 'Destroy', router, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Router', new_router_path %>

app/views/routers/new.html.erb
<h1>New Router</h1>

<%= render 'form', router: @router %>

<%= link_to 'Back', routers_path %>

app/views/routers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @router.name %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @router.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @router.longitude %>
</p>

<%= link_to 'Edit', edit_router_path(@router) %> |
<%= link_to 'Back', routers_path %>